
propbank-%.fs: propbank-ig-feat.aboutHalfDone.txt
	python dedup-features-based-on-template-names.py propbank-ig-feat.aboutHalfDone.txt $* propbank-$*.fs

all: propbank-10.fs propbank-20.fs propbank-40.fs propbank-80.fs propbank-160.fs

