/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.jhu.hlt.ikbp.data;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum EdgeType implements org.apache.thrift.TEnum {
  COREFERENCE(0),
  FRAME(1),
  ROLE(2),
  NER(3);

  private final int value;

  private EdgeType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EdgeType findByValue(int value) { 
    switch (value) {
      case 0:
        return COREFERENCE;
      case 1:
        return FRAME;
      case 2:
        return ROLE;
      case 3:
        return NER;
      default:
        return null;
    }
  }
}
