/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.jhu.hlt.ikbp.data;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum FeatureType implements org.apache.thrift.TEnum {
  REGULAR(0),
  MENTION_ID(1),
  CONCRETE_UUID(2),
  INTERCEPT(3),
  HEADWORD(4);

  private final int value;

  private FeatureType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static FeatureType findByValue(int value) { 
    switch (value) {
      case 0:
        return REGULAR;
      case 1:
        return MENTION_ID;
      case 2:
        return CONCRETE_UUID;
      case 3:
        return INTERCEPT;
      case 4:
        return HEADWORD;
      default:
        return null;
    }
  }
}
