/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.jhu.hlt.ikbp.data;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum NodeType implements org.apache.thrift.TEnum {
  ENTITY(0),
  SITUATION(1);

  private final int value;

  private NodeType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static NodeType findByValue(int value) { 
    switch (value) {
      case 0:
        return ENTITY;
      case 1:
        return SITUATION;
      default:
        return null;
    }
  }
}
